# Different themes have different required and optional fields, look at the documentation for your intended theme to see which you need and/or are available
name: Jelena Micic
background: https://images.unsplash.com/photo-1544198365-f5d60b6d8190?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80 # An image to use as a background for the site
avatar: images/profile.jpeg # The avatar/profile picture of the person's site (put image in images folder and then just the image name here)
email: jelena@friedrich-micic.de
phone: 0170 83 90 614
biography: | # The '|' Used to allow the description to go across multiple lines
  I am an experienced and reliable Quality Assurance professional with over seven years of experience, known for being a fast learner. 
  My area of interests lies in Test Automation, Test Documentation and CI/CD.
role: QA Lead
address: Forstenrieder Allee 27, 81476 Munich
social:
  github: jelimero # Your username on github 
  linkedin: jelena-micic-2b089910a/ # go to linkedin and go to your profile, your name will be at the end of the url i.e. www.linkedin.com/in/<name>
  url: https://jelimero.github.io # The URL the site will be hosted on (used by resume)
examples: true # If you want to include the example.md files in your final build (good for developing new themes)
theme: cv # The theme you want to use for your site
sections:
  - id: work_experience
    title: Work Experience
    files_order: newest_first
  - id: skills
    title: Skills
  - id: education
    title: Education
ua_code: UA-000000-0 # The UA code for google analytics
resume: true # Whether to generate the resume page or not
ignore_exif_data : false # Whether to ignore exif data for gallery images
